FROM ubuntu:latest


RUN apt-get update && apt-get -y install cron rsync openssh-client vim

# Create administrador user
RUN useradd --shell=/bin/bash --home=/home/administrador/ --create-home administrador

RUN echo "administrador"  > /etc/cron.allow

# Copy file to the cron.d directory
COPY docker/cron-jobs /etc/cron.d/cron-jobs

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/cron-jobs

# Create the log file to be able to run tail
RUN touch /var/log/cron.log
RUN chown -R administrador:administrador /var/log/cron.log

RUN mkdir /tasks
COPY docker/rsync.sh /tasks/rsync.sh
RUN chmod +x /tasks/rsync.sh
RUN chown -R administrador:administrador /tasks

# Apply cron job
# RUN crontab /etc/cron.d/cron-jobs
RUN crontab -u administrador /etc/cron.d/cron-jobs

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log
